import smtplib
import os
import sqlite3
import pandas as pd
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from dotenv import load_dotenv

load_dotenv()

def generate_html_report(latest_data_df):
    # Creating a neat HTML table from the dataframe
    table_html = latest_data_df.to_html(index=False, classes='report-table')
    
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f6f9; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; background: #ffffff; padding: 20px; border-radius: 10px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }}
            .header {{ background-color: #0b101a; color: #ffffff; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }}
            .metric-box {{ background: #f0f7ff; border-left: 4px solid #38bdf8; padding: 15px; margin: 20px 0; border-radius: 4px; }}
            .report-table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
            .report-table th {{ background-color: #1e293b; color: white; padding: 10px; text-align: left; }}
            .report-table td {{ padding: 10px; border-bottom: 1px solid #ddd; font-size: 14px; }}
            .footer {{ text-align: center; font-size: 12px; color: #888; margin-top: 30px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>Bluestock Weekly Mutual Fund Summary</h2>
            </div>
            <p>Hello Team,</p>
            <p>Please find below the weekly performance snapshot generated by the automated analytics pipeline.</p>
            
            <div class="metric-box">
                <h4>📊 Market Snapshot Insight</h4>
                <p>The analytics engine has logged the latest operational metrics. Below are the recent top fund trajectories captured in our data warehouse.</p>
            </div>
            
            <h3>📋 Top Recent Fund Records</h3>
            {table_html}
            
            <br>
            <h3>📈 Dynamic NAV Visual Trajectory</h3>
            <p>Below is the latest generated performance layout:</p>
            <img src="cid:chart_image" style="width:100%; max-width:550px; border-radius:5px;">
            
            <div class="footer">
                <p>This is an automated system-generated report from Bluestock Analytics Engine.</p>
            </div>
        </div>
    </body>
    </html>
    """
    return html_content


def send_email():
    # --- CONFIGURATION (SECURE VERSION) ---
    SENDER_EMAIL = os.getenv("EMAIL_USER", "hashmilmuhammedparammal@gmail.com")
    SENDER_PASSWORD = os.getenv("EMAIL_PASS") 
    RECEIVER_EMAIL = "hashmilmuhammedparammal@gmail.com"
    
    if not SENDER_PASSWORD:
        print("❌ Error: EMAIL_PASS not found in environment variables or .env file.")
        return
        
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    
    # 1. Fetch some recent data from database to include in the email
    db_path = os.path.join(BASE_DIR, '..', 'data', 'db', 'bluestock_mf.db')
    conn = sqlite3.connect(db_path)
    df = pd.read_sql_query("SELECT nav_date, amfi_code, nav FROM fact_nav ORDER BY nav_date DESC LIMIT 5", conn)
    conn.close()

    # 2. Setup the MIME Email Structure
    msg = MIMEMultipart('related')
    msg['Subject'] = "📊 Bluestock Weekly Analytics Report [Automated]"
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL

    # 3. Attach HTML Content
    html_body = generate_html_report(df)
    msg_html = MIMEText(html_body, 'html')
    msg.attach(msg_html)

    # 4. Embed a visual chart from reports/ directory (e.g., sector_hhi_chart.png or any available png)
    chart_path = os.path.join(BASE_DIR, '..', 'reports', 'sector_hhi_chart.png')
    
    # Fallback to any placeholder if the specific chart is missing
    if not os.path.exists(chart_path):
        # Create a dummy image path or use another visual from your reports folder
        chart_path = os.path.join(BASE_DIR, '..', 'reports', 'Dashboard - Page1.png')

    if os.path.exists(chart_path):
        with open(chart_path, 'rb') as f:
            img_data = f.read()
        msg_image = MIMEImage(img_data)
        msg_image.add_header('Content-ID', '<chart_image>')
        msg_image.add_header('Content-Disposition', 'inline', filename=os.path.basename(chart_path))
        msg.attach(msg_image)

    # 5. Connect to SMTP Server and Send Email
    try:
        print("Connecting to Gmail SMTP Server...")
        server = smtplib.SMTP('smtp.gmail.com', 577) # TLS Port
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        print("Login successful! Sending email...")
        server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
        server.quit()
        print("🚀 Email Report sent successfully!")
    except Exception as e:
        # Retry with Port 465 if Port 587 faces network restrictions
        try:
            server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
            server.quit()
            print("🚀 Email Report sent successfully via SSL (Port 465)!")
        except Exception as ssl_err:
            print(f"❌ Failed to send email: {e} | SSL Fallback error: {ssl_err}")

if __name__ == "__main__":
    send_email()